#!/bin/bash
FILENAME="$1"
echo "Simuino uploading $FILENAME"
if [ -f $FILENAME ]; 
then
cp $1 servuino/sketch.pde
cd servuino
g++ -O2 -o servuino servuino.c -lncurses
./servuino $2
cd ..
./simuino servuino/data.su
else
echo "Sketch does not exist" $1
fi
